name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 2.1.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation:
  meta:
  plugin_platform_interface:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  flutter_lints: ^1.0.3
