name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 2.1.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
  stripe_ios:
  stripe_platform_interface:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3



